version: "3.8"

services:
  openresty:
    build:
      context: openresty
    container_name: openresty
    volumes:
      - ./wwwroot:/data/wwwroot
    ports:
      - 8080:80
    expose:
      - 8080
    networks:
      - openresty
  redis:
    image: redis:alpine3.15
    container_name: openresty_redis
    ports:
      - 6378:6379
    expose:
      - 6378
    networks:
      - openresty
    
networks:
  openresty:
